### ISSUE TITLE
armv7s

### ISSUE THREAD

**Issue by hellocoral** [besport/PocoMobile#1]
Could you update for armv7s architectures?

**Comment by fxthomas** [comment]
I don't have time to do much with Poco right now, so I just added armv7s to the scripts. Also, last time I checked there was something wrong with the generated frameworks, so if this doesn't work, let me know.

**Comment by hellocoral** [comment]
it seems to have some compile errors,and it doesn't make armv7s librarys after bash finished.

"include/Poco/Crypto/CipherImpl.h:47:25: error: openssl/evp.h: No such file or directory
src/CipherFactory.cpp:46:25: error: openssl/err.h: No such file or directory
*\* Compiling src/FTPClientSession.cpp (debug, static)
make[1]: **\* [/Users/hellocoral/temp/PocoMobile/Source/Crypto/obj/iPhoneOS/armv7s/debug_static/CipherFactory.o] Error 1
make: **\* [Crypto-libexec] Error 2
make: **\* Waiting for unfinished jobs....
*\* Compiling src/FTPStreamFactory.cpp (debugg, static)"
